#line 2 "bisonCompilador.lex.c"

#line 4 "bisonCompilador.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[244] =
    {   0,
        0,    0,    0,    0,    0,    0,   50,   48,   29,   48,
       48,   12,   48,   48,   30,   31,    9,    7,    4,    8,
        2,   10,    6,    3,   23,    5,   22,   36,   43,   32,
       33,   11,   48,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       34,   48,   35,   48,   42,   42,   49,   21,    0,   44,
        0,   39,   19,   27,    0,   45,   17,   13,   46,   15,
       14,   16,    1,   40,    0,   18,    0,    6,   25,   20,
       24,   43,   43,   43,   43,   43,    0,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   37,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   37,
       43,   43,   28,   26,   41,   47,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   37,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   37,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   38,   43,   43,   43,   37,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       37,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   37,   43,   43,   43,   37,   43,   43,
       37,   43,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,   22,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,    1,   25,   26,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   23,   23,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   23,   23,
       23,   23,   48,   49,   50,   51,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    2,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[252] =
    {   0,
        0,    0,  266,  260,    0,    0,  268,  675,  242,  247,
      246,  223,  220,  205,  675,  675,  175,   40,  675,   39,
      178,   47,   47,  675,  171,  160,  157,  675,   38,  675,
      675,  675,   44,   49,   53,   51,   57,   62,   79,   86,
       80,   88,   89,   58,   94,   94,  100,  105,  107,  110,
      675,  124,  675,  148,  675,  138,  675,  675,  127,  675,
      124,  675,  675,  675,   91,  675,  675,  675,   95,  675,
      675,  675,  675,  675,   93,  675,   74,  129,  675,  675,
      675,   55,  131,  132,  133,  134,  135,  136,  138,  139,
      140,  152,  154,  155,  157,  170,  171,  172,  175,  187,

      189,  190,  191,  192,  193,  194,  195,  206,  209,  213,
      214,  217,  225,  222,  228,  233,  239,  240,  242,  247,
      246,  262,  675,  675,  675,   60,  265,  266,  267,  273,
      279,  284,  282,  285,  286,  291,  299,  293,  305,  306,
      310,  311,  313,  318,  317,  324,  331,  332,  325,  333,
      337,  344,  346,  353,  355,  357,  360,  364,  368,  371,
      373,  375,  380,  382,  389,  400,  393,  401,  404,  406,
      407,  409,  418,  137,  421,  426,  429,  433,  435,  441,
      442,  447,  453,  454,  456,  458,  459,  467,  473,  470,
      475,  476,  478,  482,  487,  495,  499,  502,  507,  506,

      508,  237,  510,  514,  515,  523,  531,  532,  538,  539,
      545,  546,  547,  318,  552,  560,  551,  553,  558,  572,
      573,  575,  577,  578,  365,  558,  592,  590,  440,  411,
      598,  604,  606,  607,  609,  610,  612,  611,  618,  505,
      623,  624,  675,  664,  666,  668,  670,  672,   71,   67,
       52
    } ;

static yyconst flex_int16_t yy_def[252] =
    {   0,
      243,    1,  244,  244,  245,  245,  243,  243,  243,  246,
      247,  243,  243,  248,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  249,  243,
      243,  243,  250,  249,  249,  249,  249,   35,  249,  249,
      249,  249,   35,  249,  249,   35,   35,   35,   35,  249,
      243,  243,  243,  243,  243,  243,  243,  243,  246,  243,
      247,  243,  243,  243,  248,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  247,  243,  243,  243,  243,  243,
      243,  251,  249,  251,  251,  249,  250,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  243,  243,  243,  243,  251,  251,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,   41,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,   41,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,   41,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,   41,   41,  249,  249,   41,   35,
      249,  249,  249,  249,  249,  249,  249,  249,  249,   41,
      249,  249,    0,  243,  243,  243,  243,  243,  243,  243,
      243
    } ;

static yyconst flex_int16_t yy_nxt[727] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   29,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   29,   47,   48,   49,   29,   50,   51,   52,   53,
       54,   68,   71,  127,   82,   69,   69,   74,   72,   70,
       85,   77,   75,   78,   84,   82,   76,   82,   86,   82,
       87,   82,   83,   82,   82,   84,  126,   84,   88,   84,
       92,   84,   95,   84,   84,   89,   96,   90,   93,  100,
      126,   91,   94,   97,   62,   82,   82,  101,   66,   98,

       99,   83,   82,  112,   82,   84,   84,  102,  103,   77,
       82,   69,   84,  105,   84,  104,  110,  106,  107,  108,
       84,  115,  103,  109,  111,   62,   82,  117,   83,   83,
       60,  118,   83,  116,   83,   83,   84,  113,  114,  119,
      120,  122,  121,   77,   83,   78,   83,   82,   82,  128,
       82,   85,   82,  125,   82,   82,   82,   84,   84,   84,
       84,   87,   84,  129,   84,   84,   84,  124,   82,  132,
       82,   82,  123,   82,   83,   83,   81,  130,   84,   80,
       84,   84,  133,   84,  131,  135,   82,   82,   82,  137,
       79,   82,   73,  136,   67,  134,   84,   84,   84,  103,

      138,   84,  139,   82,  141,   82,   82,   82,   82,   82,
       82,   82,   66,   84,  140,   84,   84,   84,   84,   84,
       84,   84,   82,  142,  147,   82,   64,  103,  143,   82,
       82,  144,   84,   82,  146,   84,  145,  148,   82,   84,
       84,   82,   63,   84,   82,  152,  149,   62,   84,   82,
       60,   84,  150,  153,   84,   82,   82,  151,   82,   84,
      103,   58,   82,   82,  154,   84,   84,  243,   84,  155,
       56,  156,   84,   84,   83,   83,   56,  157,   82,  160,
      158,   82,  128,   82,  159,  161,  162,  243,   84,   82,
      103,   84,   84,   84,  243,   82,  243,  164,   82,   84,

       82,   82,   82,  243,  163,   84,  165,   82,   84,   82,
       84,   84,   84,  168,  243,   82,  166,   84,  167,   84,
      243,   82,   82,  172,  103,   84,   82,   82,  169,   82,
      171,   84,   84,   82,   82,  170,   84,   84,  173,   84,
       82,   82,  177,   84,   84,  174,  178,   82,   82,   82,
       84,   84,  175,   82,  176,   83,   83,   84,   84,   84,
       82,  179,   82,   84,  243,  183,  180,  181,  103,   82,
       84,   82,   84,   82,  182,  243,   82,  184,  243,   84,
       82,   84,  185,   84,   82,  103,   84,   82,  188,   82,
       84,   82,  186,  189,   84,  190,   82,   84,   82,   84,

      187,   84,   83,   83,  243,   82,   84,  191,   84,   82,
      193,  192,  103,  194,  103,   84,   82,   82,  243,   84,
       82,  243,   82,   82,  195,   82,   84,   84,  197,  243,
       84,  196,   84,   84,   82,   84,  201,   82,  237,  198,
      103,  200,   82,  243,   84,   82,   83,   84,  199,   82,
      238,   82,   84,  202,  243,   84,  203,   82,   82,   84,
      205,   84,  103,   82,  204,  182,  243,   84,   84,   82,
       82,  243,   82,   84,   82,   82,  206,   83,   83,   84,
       84,  103,   84,   82,   84,   84,   82,  207,  208,   82,
      210,   82,   82,   84,   82,  243,   84,  243,   82,   84,

      209,   84,   84,   82,   84,  215,  243,  214,   84,  211,
      243,   82,  103,   84,  212,   82,  217,  213,   82,  243,
      216,   84,   82,   82,   82,   84,   82,  243,   84,  103,
       82,   82,   84,   84,   84,  243,   84,  218,  222,   82,
       84,   84,   83,   83,  220,  219,  182,   82,   82,   84,
      243,  103,  221,  223,   82,   82,  243,   84,   84,  226,
      224,   82,   82,   82,   84,   84,  225,   82,   82,   82,
      243,   84,   84,   84,   82,  243,   82,   84,   84,   84,
      227,  229,  231,  228,   84,  230,   84,  182,   82,   82,
      182,   82,  182,   82,   82,   83,   83,  103,   84,   84,

      182,   84,  243,   84,   84,  243,   82,  243,   82,  243,
      233,  243,  186,  235,   82,  234,   84,  232,   84,  236,
       82,  103,   82,   82,   84,   82,   82,   82,   82,  239,
       84,  240,   84,   84,   82,   84,   84,   84,   84,   82,
       82,  243,  243,  243,   84,  243,  243,  243,  211,   84,
       84,  241,  243,  103,  238,  103,  243,  243,  243,  243,
      242,  243,  243,  182,   55,   55,   57,   57,   59,   59,
       61,   61,   65,   65,    7,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243
    } ;

static yyconst flex_int16_t yy_chk[727] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   18,   20,  251,   29,   20,   18,   22,   20,   18,
       33,   23,   22,   23,   29,   34,   22,   36,  250,   35,
       33,   82,  249,   37,   44,   34,  126,   36,   34,   35,
       35,   82,   36,   37,   44,   34,   36,   34,   35,   38,
       77,   34,   35,   37,   75,   39,   41,   38,   65,   37,

       37,   38,   40,   44,   42,   39,   41,   38,   39,   69,
       45,   69,   40,   40,   42,   39,   43,   41,   41,   42,
       45,   46,   41,   42,   43,   61,   50,   47,   43,   46,
       59,   47,   48,   46,   49,   47,   50,   45,   45,   47,
       48,   50,   49,   78,   48,   78,   49,   83,   84,   85,
       86,   87,   88,   56,   89,   90,   91,   83,   84,   85,
       86,   87,   88,   88,   89,   90,   91,   54,   92,   91,
       93,   94,   52,   95,  174,  174,   27,   89,   92,   26,
       93,   94,   92,   95,   90,   93,   96,   97,   98,   95,
       25,   99,   21,   94,   17,   92,   96,   97,   98,   96,

       95,   99,   97,  100,   99,  101,  102,  103,  104,  105,
      106,  107,   14,  100,   98,  101,  102,  103,  104,  105,
      106,  107,  108,  100,  107,  109,   13,  101,  102,  110,
      111,  104,  108,  112,  106,  109,  105,  108,  114,  110,
      111,  113,   12,  112,  115,  111,  109,   11,  114,  116,
       10,  113,  109,  112,  115,  117,  118,  110,  119,  116,
      113,    9,  121,  120,  114,  117,  118,    7,  119,  115,
        4,  116,  121,  120,  202,  202,    3,  117,  122,  119,
      118,  127,  128,  129,  118,  120,  121,    0,  122,  130,
      120,  127,  128,  129,    0,  131,    0,  129,  133,  130,

      132,  134,  135,    0,  122,  131,  130,  136,  133,  138,
      132,  134,  135,  133,    0,  137,  131,  136,  132,  138,
        0,  139,  140,  138,  134,  137,  141,  142,  135,  143,
      137,  139,  140,  145,  144,  136,  141,  142,  139,  143,
      146,  149,  143,  145,  144,  140,  144,  147,  148,  150,
      146,  149,  141,  151,  142,  214,  214,  147,  148,  150,
      152,  145,  153,  151,    0,  149,  146,  147,  151,  154,
      152,  155,  153,  156,  148,    0,  157,  150,    0,  154,
      158,  155,  152,  156,  159,  153,  157,  160,  156,  161,
      158,  162,  154,  157,  159,  158,  163,  160,  164,  161,

      155,  162,  225,  225,    0,  165,  163,  159,  164,  167,
      163,  160,  161,  164,  162,  165,  166,  168,    0,  167,
      169,    0,  170,  171,  165,  172,  166,  168,  167,    0,
      169,  166,  170,  171,  173,  172,  171,  175,  230,  168,
      172,  170,  176,    0,  173,  177,  230,  175,  169,  178,
      230,  179,  176,  173,    0,  177,  175,  180,  181,  178,
      178,  179,  179,  182,  177,  176,    0,  180,  181,  183,
      184,    0,  185,  182,  186,  187,  180,  229,  229,  183,
      184,  184,  185,  188,  186,  187,  190,  181,  183,  189,
      187,  191,  192,  188,  193,    0,  190,    0,  194,  189,

      185,  191,  192,  195,  193,  193,    0,  192,  194,  188,
        0,  196,  189,  195,  190,  197,  195,  191,  198,    0,
      194,  196,  200,  199,  201,  197,  203,    0,  198,  198,
      204,  205,  200,  199,  201,    0,  203,  196,  203,  206,
      204,  205,  240,  240,  200,  197,  199,  207,  208,  206,
        0,  205,  201,  204,  209,  210,    0,  207,  208,  208,
      206,  211,  212,  213,  209,  210,  207,  217,  215,  218,
        0,  211,  212,  213,  219,    0,  216,  217,  215,  218,
      209,  212,  215,  210,  219,  213,  216,  216,  220,  221,
      217,  222,  218,  223,  224,  226,  226,  219,  220,  221,

      226,  222,    0,  223,  224,    0,  228,    0,  227,    0,
      222,    0,  221,  224,  231,  223,  228,  220,  227,  227,
      232,  228,  233,  234,  231,  235,  236,  238,  237,  231,
      232,  232,  233,  234,  239,  235,  236,  238,  237,  241,
      242,    0,    0,    0,  239,    0,    0,    0,  233,  241,
      242,  235,    0,  236,  237,  241,    0,    0,    0,    0,
      239,    0,    0,  242,  244,  244,  245,  245,  246,  246,
      247,  247,  248,  248,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analisisCompilador.flex"
#line 4 "analisisCompilador.flex"
#include <stdio.h>
#include <string.h>
#include "bisonCompilador.tab.h"
extern YYSTYPE yylval


#line 712 "bisonCompilador.lex.c"

#define INITIAL 0
#define comentario 1
#define bloquefuncion 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 63 "analisisCompilador.flex"


#line 904 "bisonCompilador.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 244 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 675 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 65 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "AGREGACION DE CADENAS: (\")", yytext , yylineno);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "PUNTO: (\")", yytext , yylineno);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "DOBLE PUNTO: (\")", yytext , yylineno);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "SEPARADOR: (\")", yytext , yylineno);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 69 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "ASIGNACION: (\")", yytext , yylineno);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 71 "analisisCompilador.flex"
yylval = atoi(yytext); return NUMERO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "analisisCompilador.flex"
return '+';
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "analisisCompilador.flex"
return '-';
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "analisisCompilador.flex"
return '*';
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "analisisCompilador.flex"
return '/';
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "analisisCompilador.flex"
return '^';
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MODULO: (\")", yytext , yylineno);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "INCREMENTACION: (\")", yytext , yylineno);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "DECREMENTACION: (\")", yytext , yylineno);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "SUMAR CON: (\")", yytext , yylineno);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "RESTAR CON: (\")", yytext , yylineno);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MULTIPLICAR CON: (\")", yytext , yylineno);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "DIVIDIR CON: (\")", yytext , yylineno);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MODULAR CON: (\")", yytext , yylineno);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "IGUALDAD: (\")", yytext , yylineno);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "DIFERENCIA: (\")", yytext , yylineno);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MAYOR QUE: (\")", yytext , yylineno);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MENOR QUE: (\")", yytext , yylineno);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MAYOR E IGUAL QUE: (\")", yytext , yylineno);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 95 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "MENOR E IGUAL QUE: (\")", yytext , yylineno);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "COINCIDE ER: (\")", yytext , yylineno);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "AND: (\")", yytext , yylineno);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "OR: (\")", yytext , yylineno);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "NEGACION: (\")", yytext , yylineno);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "INICIO PARENTESIS: (\")", yytext , yylineno);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "analisisCompilador.flex"
{printf("PARENTESIS DERECHO: %s\n",yytext);}{fprintf(yyout, "%-60s %-30s %-15i\n", "FIN PARENTESIS: (\")", yytext , yylineno);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 105 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "INICIO CORCHETE: (\")", yytext , yylineno);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 106 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "FIN CORCHETE: (\")", yytext , yylineno);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "INICIO LLAVE: (\")", yytext , yylineno);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "FIN LLAVE: (\")", yytext , yylineno);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 111 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "CONDICION: (\")", yytext , yylineno);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 113 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "PALABRA RESERVADA: (\")", yytext , yylineno);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "PALABRA BOOLEANA: (\")", yytext , yylineno);}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 117 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "COMENTARIO DE UNA LINEA: (\")", yytext , yylineno);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "analisisCompilador.flex"
{BEGIN comentario; fprintf(yyout, "%-60s %-30s %-15i\n", "INICIO COMENTARIO: (\")", yytext , yylineno);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "analisisCompilador.flex"
{BEGIN INITIAL; fprintf(yyout, "%-60s %-30s %-15i\n", "FIN COMENTARIO: (\")", yytext , yylineno);}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 121 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "CONTENIDO DE COMENTARIO: (\")", yytext , yylineno);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "VARIABLE: (\")", yytext , yylineno);}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 125 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "CADENA: (\")", yytext , yylineno);}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 126 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "CADENA: (\")", yytext , yylineno);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "NUMERO ENTERO: (\")", yytext , yylineno);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "analisisCompilador.flex"
{fprintf(yyout, "%-60s %-30s %-15i\n", "NUMERO DECIMAL: (\")", yytext , yylineno);}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 131 "analisisCompilador.flex"
{}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 133 "analisisCompilador.flex"
ECHO;
	YY_BREAK
#line 1237 "bisonCompilador.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comentario):
case YY_STATE_EOF(bloquefuncion):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 244 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 244 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 243);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 133 "analisisCompilador.flex"



int main(int argc,char *argv[]) {
    char pathI[100] = "./pruebas/";
    char pathO[100] = "./pruebas/";
    strcat(pathI, argv[1]);
    strcat(pathO, argv[2]);
    
    yyin = fopen(pathI, "rt");
    yyout = fopen(pathO, "wt");
    
    if (yyin == NULL || yyout == NULL) {
        printf("\nNo se puede abrir el archivo: %s\n", pathO);
        exit(-1);
    } else {
        fprintf(yyout,"COMPILADORES Y LENGUAJES FORMALES\n\n\n");
        fprintf(yyout,"%-60s %-30s %-15s \n", "TOKEN","LEXEMA", "LINEA");
        fprintf(yyout,"%-60s %-30s %-15s \n", "-----","------", "------\n");
        yylex();
        printf("\nFichero %s generado correctamente!!\n", pathO);
    }

    fclose(yyin);
    fclose(yyout);
    return 0;
}
